version: 0.2

phases:

  pre_build:
    commands:
      - echo "Checking AWS identity..."
      - aws sts get-caller-identity

      - echo "Getting AWS account ID..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "Setting ECR repository..."
      - ECR_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/employee-pro

      - echo "ECR Repository = $ECR_REPOSITORY_URI"

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "IMAGE_TAG = $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image with commit tag..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG

      - echo "Pushing latest Docker image..."
      - docker push $ECR_REPOSITORY_URI:latest

      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"employee-container","imageUri":"%s"}]' "$ECR_REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

      - echo "Generated imagedefinitions.json:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
